cloud.cloudflare.r2.credentials.access-key=${R2_ACCESS_KEY}
cloud.cloudflare.r2.credentials.secret-key=${R2_SECRET_KEY}
cloud.cloudflare.r2.endpoint=${R2_ENDPOINT}
cloud.cloudflare.r2.region=auto
cloud.cloudflare.r2.bucket=${R2_BUCKET_NAME}
cloud.cloudflare.r2.presigned.expiration-minutes=5
